### ISSUE TITLE
Unclarity regarding data structure of labels

### ISSUE THREAD

**Issue by DanielStrahnen** [neil-gallagher/CSFA#2]
When trying to run the _trainCSFA_ function to obtain the dCSFA, I stumbled upon the following question:
As suggested in the description of _trainCSFA_, the target information for the classifier is stored in labels.windows as an 60x1 array containing ones for a positive and zeros for a negative event. However, _initModel_ transforms the target variable into a 60x2 by adding another array below with ones and zeros swapped. Subsequently _balanceClasses_ bails out an error because upsampling is not possible because sum(labels==1) and sum(labels==0) are both an array of the same length. Also, _fitcsvm_ requires the response variable to be a vector, not a 2-row matrix.
Most likely I'm missing something here, but I would appreciate Clarification on this.
Thanks and best regards
Daniel

**Comment by neil-gallagher** [comment]
Hi Daniel,

Thanks for reaching out with the issues you're having.

A few questions? 
1. Just to make sure, are you using the most recent commit on the master branch?

2. Do you know which line in initModel is converting the target variable into a matrix? I don't believe this is the intended behavior; initModel should send the vector 'as is' into the dCSFA constructor.
 
3. Do you experience any issues when you try to run the same data through an unsupervised CSFA model?

Lastly, you may also want to try using the most recent commit from the _stochFreq_ branch. I've changed some of the initialization behavior (for instance balanceClasses is no longer it's own method in the dCSFA class). These updates may have resolved your issue and that branch should maintain all of the functionality in the master branch. I was planning on merging it into the master branch within the next few days anyway.

**Comment by DanielStrahnen** [comment]
Hi Neil,

Many thanks for your suggestions! After using the stochFreq branch the matrix conversion of the label vector didn't occur anymore! And running the unsupervised CSFA returns reasonable returns (scores + train/holdoutModels). 
However, when specifying a discriminative Model after more than 20 iterations CSFA.gradient returns the following warning: _Matrix is close to singular or badly scaled. Results may be inaccurate. RCOND = -1.000000e+00_. That is because the input model _self_ to CSFA.gradient is now exclusively filled with NaNs. I'm struggling to find the solution to this, particularly in view of the unsupervised CSFA working fine. Also this warning does not occur when I only use 1 factor for the classifier (setting modelOpts.dIdx = 1), but when setting modeOpts.dIdx = 10 the warning occurs.
Otherwise I'm using all of your default configuration.
Sorry for bothering you, but thanks again for sharing your code!

**Comment by neil-gallagher** [comment]
I have not seen an issue with the model being filled with NaNs before. My guess is that the gradients for the supervised portion of the model are exploding and causing things to be unstable. Perhaps try setting modelOpts.lambda to something very small, maybe 1e-6. Then if that works try increasing it until you get to a point where the model runs without issue and you still get some impact from supervision.

**Comment by DanielStrahnen** [comment]
Thanks for the suggestion, lower numbers of iterations and factors resolved the issue. However, I am not sure how to format my data regarding missing channels. As suggested in the header of _preprocessDeap_ missing channels are filled with NaN's before running _preprocessDeap_. Consequently, xFft also contains NaN's for the respective channels, but trainCSFA returns an error because _nnmf_ checks if the matrix contains NaN's. Data from multiple mice are concatenated and information about individual subjects is stored in labels.windows.subjectID.

**Comment by neil-gallagher** [comment]
Unfortunately accounting for missing channels isn't a feature that is fully supported by the code right now.

In practice I have always ended up averaging together multiple channels into one 'super channel' and just eliminate the small amount of recordings where all of the channels within a 'super channel' are missing. Is that something that would be possible with your application?

**Comment by DanielStrahnen** [comment]
Unfortunately I used single channel electrodes so there is no way to average anything. Do you plan to implement the marginalization or simulation of missing channels in the covariance matrix as described in the paper in your online code?

**Comment by neil-gallagher** [comment]
I had not planned on implementing either. Unfortunately doing so would require restructuring the gradient calculation portion of the code in a way that I think would slow it down substantially. How crucial is including the recordings with missing channels to your application?

**Comment by DanielStrahnen** [comment]
Most of my recordings don't contain all channels and averaging isn't possible since I used single channel electrodes. So unfortunately, the dCSFA doesn't seem applicable to my data.

**Comment by neil-gallagher** [comment]
Sorry we couldn't make dCSFA work for you right now. Learning from data with missing channels is something we had been meaning to implement, but never got around to. If I am able to make those changes at some point in the near future I will reach out to let you know.

**Comment by bboyfx** [comment]
Is there still  significance in performing a spectral factors analysis of one brain region if I only collected local field potential signals from one brain area?

**Comment by neil-gallagher** [comment]
Certainly. With only a single brain area, the problem just simplifies to having each factor represent one component of the spectral activity that appears in your region over the course of the recordings. Let me know if you have any questions running this code on data from a single region (although maybe open a new issue rather than continuing the conversation here, since the topic isn't super relevant to this issue).

**Comment by bboyfx** [comment]
Thank you for your prompt response and for clarifying how the code works with data from a single brain area. I appreciate your suggestion to open a new issue if I have further questions on this topic. I will definitely keep that in mind. Thanks again!
